name: coast_env
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - anndata=0.11.3
  - anyio=4.11.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - array-api-compat=1.12.0
  - arrow=1.4.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.10.19
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.16
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.6.15
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - json5=0.12.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - legacy-api-wrap=1.4.1
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=20.1.8
  - libcups=2.4.2
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenjpeg=2.5.4
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.2.13
  - llvm-openmp=8.0.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.2.1
  - mesalib=25.1.5
  - mistune=3.1.4
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - natsort=8.4.0
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.89.1
  - openh264=2.1.1
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.2.5
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - qhull=2020.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebengine=6.9.2
  - qtwebsockets=6.9.2
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - scanpy=1.11.5
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info2=0.2.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - spirv-tools=2025.4
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - tbb=2022.2.0
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.3.0
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - argon2-cffi-bindings==25.1.0
    - brotli==1.2.0
    - cffi==2.0.0
    - contourpy==1.3.1
    - debugpy==1.8.17
    - fonttools==4.60.1
    - fsspec==2025.9.0
    - gmpy2==2.2.1
    - h5py==3.12.1
    - ipykernel==6.30.1
    - jsonpointer==3.0.0
    - kiwisolver==1.4.9
    - llvmlite==0.44.0
    - markupsafe==3.0.3
    - matplotlib==3.9.4
    - numba==0.61.2
    - numpy==2.2.6
    - pandas==2.3.3
    - pillow==11.3.0
    - psutil==7.1.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - rpds-py==0.28.0
    - scikit-learn==1.7.2
    - scipy==1.15.2
    - send2trash==1.8.2
    - statsmodels==0.14.5
    - sympy==1.13.1
    - terminado==0.15.0
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - tornado==6.5.2
    - umap-learn==0.5.9.post2
    - unicodedata2==16.0.0

